CREATE TABLE FRIENDS (
  U1 BIGINT NOT NULL,
  U2 BIGINT NOT NULL,
  CONSTRAINT PK_friends_id PRIMARY KEY (U1, U2),
  FOREIGN KEY (U1) REFERENCES USERS(ID),
  FOREIGN KEY (U2) REFERENCES USERS(ID),
  STATUS BOOLEAN NOT NULL
);